name: Build

on:
  push:
    branches: [ulysses]
    tags: [v*.*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719 # 16.0
      - name: Build
        run: ./gradlew --no-daemon build
      - name: Sign
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: 36.0.0
      - name: Rename
        run: mv ${{ steps.sign.outputs.signedReleaseFile }} app-release.apk
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app-release.apk

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: apk
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app-release.apk
