name: Android Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > app/keystore.jks

      - name: Create gradle.properties
        run: |
          mkdir -p ~/.gradle
          cat <<EOF >> ~/.gradle/gradle.properties
          storeFile=keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Extract Version from Gradle (KTS)
        id: version
        run: |
            VERSION_NAME=$(grep 'versionName =' app/build.gradle.kts | sed 's/.*"\(.*\)".*/\1/')
            echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Upload Release APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: release-apk
            path: app/build/outputs/apk/release/app-release.apk

  release:
        needs: build
        runs-on: ubuntu-latest

        steps:
          - name: Download APK Artifact
            uses: actions/download-artifact@v4
            with:
              name: release-apk
              path: .

          - name: Create GitHub Release
            uses: softprops/action-gh-release@v2
            with:
              tag_name: v${{ needs.build.outputs.version_name }}
              name: Release v${{ needs.build.outputs.version_name }}
              files: app-release.apk
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}